#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_PROPERTIES="${ROOT_DIR}/android/local.properties"

resolve_sdk_root() {
  if [[ -n "${ANDROID_HOME:-}" && -d "${ANDROID_HOME}" ]]; then
    printf '%s' "${ANDROID_HOME}"
    return
  fi

  if [[ -n "${ANDROID_SDK_ROOT:-}" && -d "${ANDROID_SDK_ROOT}" ]]; then
    printf '%s' "${ANDROID_SDK_ROOT}"
    return
  fi

  for candidate in \
    "${HOME}/Android/Sdk" \
    "/data/dev/android/sdk/Sdk" \
    "/data/dev/android/sdk"; do
    if [[ -d "${candidate}/platform-tools" ]]; then
      printf '%s' "${candidate}"
      return
    fi
  done

  echo "Android SDK not found. Set ANDROID_HOME to your SDK root." >&2
  exit 1
}

resolve_ndk_dir() {
  local sdk_root="$1"
  local required_ndk_version="28.2.13676358"

  if [[ -d "${sdk_root}/ndk/${required_ndk_version}" ]]; then
    printf '%s/ndk/%s' "${sdk_root}" "${required_ndk_version}"
    return
  fi

  local newest_ndk
  newest_ndk="$(find "${sdk_root}/ndk" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort -V | tail -n 1 || true)"

  if [[ -n "${newest_ndk}" ]]; then
    printf '%s' "${newest_ndk}"
    return
  fi

  echo "Android NDK not found under ${sdk_root}/ndk. Install NDK ${required_ndk_version}." >&2
  exit 1
}

SDK_ROOT="$(resolve_sdk_root)"
NDK_DIR="$(resolve_ndk_dir "${SDK_ROOT}")"

if [[ ! -d "${NDK_DIR}" ]]; then
  echo "CoMaps requires NDK 28.2.13676358 under ${SDK_ROOT}/ndk." >&2
  exit 1
fi

cat > "${LOCAL_PROPERTIES}" <<EOF
## Generated by apps/mobile/scripts/write-android-local-properties.sh
sdk.dir=${SDK_ROOT}
EOF

echo "Wrote ${LOCAL_PROPERTIES}"
echo "  sdk.dir=${SDK_ROOT}"
echo "  (ndk.dir omitted — each module uses android.ndkVersion; CoMaps requires 28.2.13676358)"
